from dataclasses import dataclass

from chromadb import EmbeddingFunction
from sentence_transformers import SentenceTransformer

'''
NOTE: Found out that dataclasses are getting initialized as soon as we import this module, or 
    if we run this script. Workaround: outsource the attributes that we don't want 
    to initialize right away.
'''

'''
The EmbeddingModelsTesting.requires_validation models are the top 5 models scoring 
the highest on the MTEB, using the following filters:

-- Prebuilt benchmark: MTEB(Multilingual, v1)
-- Languages: all
-- Task types: InstructionRetrieval, Reranking, Retrieval, STS 
-- Domains: academic, encyclopaedic, government, legal, subtitles, web, written
-- Added and removed tasks: default values.
'''

@dataclass
class ModelsConfig:
    models={"multi_qa":"multi-qa-mpnet-base-dot-v1",
            "mpnet":"all-mpnet-base-v2", 
            "biling_lg":"Lajavaness/bilingual-embedding-large"}
    
    models_similarity_fn={"multi-qa-mpnet-base-dot-v1":"ip",
                          "all-mpnet-base-v2":"cosine",
                          "Lajavaness/bilingual-embedding-large":"N/A"}
    
    models_untested={"inf_retriever":"infly/inf-retriever-v1-1.5b", 
                     "qwen2_small":"Alibaba-NLP/gte-Qwen2-1.5B-instruct",
                     "qwen2_large": "Alibaba-NLP/gte-Qwen2-7B-instruct",
                     "sfr_mistral": "Salesforce/SFR-Embedding-Mistral",
                     "linq_mistral":"Linq-AI-Research/Linq-Embed-Mistral"}

@dataclass
class VectorDBDataFiles:
    databases = [
        {
            "name": "labour",
            "is_default": True,
            "save_html": True,
            "languages": ["en", "fr"],
            "ressource_name": {
                "en": "Labour",
                "fr": "Travail"
            },
            "ipg": {
                "en": "https://www.canada.ca/en/employment-social-development/programs/laws-regulations/labour/interpretations-policies.html",
                "fr": "https://www.canada.ca/fr/emploi-developpement-social/programmes/lois-reglements/travail/interpretations-politiques.html"
            },
            "law": {
                "en": [
                    ("clc", "https://laws-lois.justice.gc.ca/eng/acts/l-2/"),
                    ("clsr", "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._986/")
                ],
                "fr": [
                    ("clc", "https://laws-lois.justice.gc.ca/fra/lois/l-2/"),
                    ("clsr", "https://laws-lois.justice.gc.ca/fra/reglements/C.R.C.%2C_ch._986/")
                ]
            },
            "page": {
                "en": [
                    ("LABOUR", "https://www.canada.ca/en/employment-social-development/corporate/portfolio/labour.html"),
                    ("WORKPLACE", "https://www.canada.ca/en/services/jobs/workplace.html"),
                    ("LABOUR-REPORTS", "https://www.canada.ca/en/employment-social-development/corporate/portfolio/labour/programs/labour-standards/reports.html"),
                    ("LABOUR-STANDARDS", "https://www.canada.ca/en/services/jobs/workplace/federal-labour-standards.html"),
                    ("COMPENSATION", "https://www.canada.ca/en/services/jobs/workplace/health-safety/compensation.html"),
                    ("HEALTH-SAFETY", "https://www.canada.ca/en/services/jobs/workplace/health-safety.html")
                ],
                "fr": [
                    ("LABOUR", "https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/travail.html"),
                    ("WORKPLACE", "https://www.canada.ca/fr/services/emplois/milieu-travail.html"),
                    ("LABOUR-REPORTS", "https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/travail/programmes/normes-travail/rapports.html"),
                    ("LABOUR-STANDARDS", "https://www.canada.ca/fr/services/emplois/milieu-travail/normes-travail-federales.html"),
                    ("COMPENSATION", "https://www.canada.ca/fr/services/emplois/milieu-travail/sante-securite/indemnisation.html"),
                    ("HEALTH-SAFETY", "https://www.canada.ca/fr/services/emplois/milieu-travail/sante-securite.html")
                ]
            },
            "page_blacklist": {
                "en": [
                    "/en/news/",
                    "/en/employment-social-development/programs/laws-regulations/labour/interpretations-policies.html"
                ],
                "fr": [
                    "/fr/nouvelles.html",
                    "/fr/emploi-developpement-social/programmes/lois-reglements/travail/interpretations-politiques.html"
                ]
            }
        },
        {
            "name": "equity",
            "languages": ["en", "fr"],
            "ressource_name": {
                "en": "Equity",
                "fr": "Équité"
            },
            "pdf": {
                "en": [
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDWEIMSUserGuide-20220224-PDF%20(1).pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/EmployerOnboardingGuide-LEEP-2024.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/Taking%20action%20on%20your%20employment%20equity%20data.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDWorkshopHowToInterpretForm2,%20parts%20D-G-20220427.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDStep-by-step%20guide%20for%20annual%20Legislated%20Employment%20Equity%20Program%20(LEEP)%20reporting.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/EmployerOnboardingGuide-FCP-2024.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDHowToImproveWorkplaceEquity-20230308-PDF.pdf"
                ],
                "fr": [
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDWEIMSUserGuideFR-20220224-PDF%20(1).pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/GuideDIntegrationPourLesEmployeurs-PLEME-2024.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/Agir%20a%20partir%20de%20vos%20donnees%20sur%20l%20equite%20en%20emploi.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDAtelierCommentInterpreterVotreFormulaire%202,%20parties%20D-G-20220428.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-Guide%20de%20preparation%20etape%20par%20etape%20du%20rapport%20annuel%20du%20Programme%20legifere%20dequite%20en%20matiere%20demploi%20(PLEME).pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/GuideDIntegrationPourLesEmployeurs-PCF-2024.pdf",
                    "https://equity.esdc.gc.ca/sgiemt-weims/maint/file/download/FP-GC-WEDCommentAmeliorerLequiteSurLeLieuDuTravailFR-20230308-PDF.pdf"
                ]
            }
        },
        {
        "name": "transport_act_reg",
        "languages": [
            "en"
        ],
        "ressource_name": {
            "en": "Transport Acts & Regulations"
        },
        "law": {
            "en": [
            [
                "C-11.2",
                "https://laws-lois.justice.gc.ca/eng/acts/C-11.2"
            ],
            [
                "C-23.4",
                "https://laws-lois.justice.gc.ca/eng/acts/C-23.4"
            ],
            [
                "M-12.01",
                "https://laws-lois.justice.gc.ca/eng/acts/M-12.01"
            ],
            [
                "N-26.5",
                "https://laws-lois.justice.gc.ca/eng/acts/N-26.5"
            ],
            [
                "C-29.7",
                "https://laws-lois.justice.gc.ca/eng/acts/C-29.7"
            ],
            [
                "M-0.8",
                "https://laws-lois.justice.gc.ca/eng/acts/M-0.8"
            ],
            [
                "S-22",
                "https://laws-lois.justice.gc.ca/eng/acts/S-22"
            ],
            [
                "U-3",
                "https://laws-lois.justice.gc.ca/eng/acts/U-3"
            ],
            [
                "E-15",
                "https://laws-lois.justice.gc.ca/eng/acts/E-15"
            ],
            [
                "Q-1.7",
                "https://laws-lois.justice.gc.ca/eng/acts/Q-1.7"
            ],
            [
                "N-7",
                "https://laws-lois.justice.gc.ca/eng/acts/N-7"
            ],
            [
                "O-2.6",
                "https://laws.justice.gc.ca/eng/acts/O-2.6"
            ],
            [
                "P-21",
                "https://laws-lois.justice.gc.ca/eng/acts/P-21"
            ],
            [
                "M-0.7",
                "https://laws-lois.justice.gc.ca/eng/acts/M-0.7"
            ],
            [
                "A-10.1",
                "https://laws-lois.justice.gc.ca/eng/acts/A-10.1"
            ],
            [
                "H-3.8",
                "https://laws-lois.justice.gc.ca/eng/acts/H-3.8"
            ],
            [
                "A-12",
                "https://laws-lois.justice.gc.ca/eng/acts/A-12"
            ],
            [
                "B-5",
                "https://laws-lois.justice.gc.ca/eng/acts/B-5"
            ],
            [
                "C-0.2",
                "https://laws-lois.justice.gc.ca/eng/acts/C-0.2"
            ],
            [
                "R-4.2",
                "https://laws-lois.justice.gc.ca/eng/acts/R-4.2"
            ],
            [
                "O-3.01",
                "https://laws-lois.justice.gc.ca/eng/acts/O-3.01"
            ],
            [
                "M-0.56",
                "https://laws-lois.justice.gc.ca/eng/acts/M-0.56"
            ],
            [
                "S-6.7",
                "https://laws-lois.justice.gc.ca/eng/acts/S-6.7"
            ],
            [
                "C-15.31",
                "https://laws-lois.justice.gc.ca/eng/acts/C-15.31"
            ],
            [
                "C-19.1",
                "https://laws-lois.justice.gc.ca/eng/acts/C-19.1"
            ],
            [
                "T-19.01",
                "https://lois-laws.justice.gc.ca/eng/acts/T-19.01"
            ],
            [
                "T-18",
                "https://laws-lois.justice.gc.ca/eng/acts/T-18"
            ],
            [
                "C-10.15",
                "https://laws-lois.justice.gc.ca/eng/acts/C-10.15"
            ],
            [
                "P-14",
                "https://laws-lois.justice.gc.ca/eng/acts/P-14"
            ],
            [
                "F-11",
                "https://laws-lois.justice.gc.ca/eng/acts/F-11"
            ],
            [
                "M-0.58",
                "https://laws-lois.justice.gc.ca/eng/acts/M-0.58"
            ],
            [
                "B-9.86",
                "https://laws-lois.justice.gc.ca/eng/acts/B-9.86"
            ],
            [
                "C-7.8",
                "https://laws-lois.justice.gc.ca/eng/acts/C-7.8"
            ],
            [
                "H-1",
                "https://laws-lois.justice.gc.ca/eng/acts/H-1"
            ],
            [
                "A-2",
                "https://laws.justice.gc.ca/eng/acts/A-2"
            ],
            [
                "M-9",
                "https://laws-lois.justice.gc.ca/eng/acts/M-9"
            ],
            [
                "P-19.3",
                "https://laws-lois.justice.gc.ca/eng/acts/P-19.3"
            ],
            [
                "C-6.7",
                "https://laws-lois.justice.gc.ca/eng/acts/C-6.7"
            ],
            [
                "M-10.01",
                "https://laws-lois.justice.gc.ca/eng/acts/M-10.01"
            ],
            [
                "A-1",
                "https://laws.justice.gc.ca/eng/acts/A-1"
            ],
            [
                "N-23.6",
                "https://laws-lois.justice.gc.ca/eng/acts/N-23.6"
            ],
            [
                "S-10.01",
                "https://laws-lois.justice.gc.ca/eng/acts/S-10.01"
            ],
            [
                "W-12.3",
                "https://lois-laws.justice.gc.ca/eng/acts/W-12.3"
            ],
            [
                "C-10.4",
                "https://laws-lois.justice.gc.ca/eng/acts/C-10.4"
            ],
            [
                "F-8",
                "https://laws-lois.justice.gc.ca/eng/acts/F-8"
            ],
            [
                "R-4",
                "https://laws-lois.justice.gc.ca/eng/acts/R-4"
            ],
            [
                "T-18.5",
                "https://laws-lois.justice.gc.ca/eng/acts/T-18.5"
            ],
            [
                "C-26",
                "https://laws-lois.justice.gc.ca/eng/acts/C-26"
            ],
            [
                "N-26.3",
                "https://laws-lois.justice.gc.ca/eng/acts/N-26.3"
            ],
            [
                "L-2",
                "https://laws-lois.justice.gc.ca/eng/acts/L-2"
            ],
            [
                "E-4.56",
                "https://laws-lois.justice.gc.ca/eng/acts/E-4.56"
            ],
            [
                "I-17.05",
                "https://laws-lois.justice.gc.ca/eng/acts/I-17.05"
            ],
            [
                "I-19.6",
                "https://laws-lois.justice.gc.ca/eng/acts/I-19.6"
            ],
            [
                "M-0.6",
                "https://laws-lois.justice.gc.ca/eng/acts/M-0.6"
            ],
            [
                "G-6",
                "https://laws-lois.justice.gc.ca/eng/acts/G-6"
            ],
            [
                "A-18.5",
                "https://laws-lois.justice.gc.ca/eng/acts/A-18.5"
            ],
            [
                "C-7.5",
                "https://laws-lois.justice.gc.ca/eng/acts/C-7.5"
            ],
            [
                "N-22",
                "https://laws.justice.gc.ca/eng/acts/N-22"
            ],
            [
                "B-8",
                "https://laws-lois.justice.gc.ca/eng/acts/B-8"
            ],
            [
                "C-33.3",
                "https://laws-lois.justice.gc.ca/eng/acts/C-33.3"
            ],
            [
                "S-6.9",
                "https://laws-lois.justice.gc.ca/eng/acts/S-6.9"
            ],
            [
                "A-10.4",
                "https://laws-lois.justice.gc.ca/eng/acts/A-10.4"
            ],
            [
                "S-1",
                "https://laws-lois.justice.gc.ca/eng/acts/S-1"
            ],
            [
                "C.R.C.,_c._109",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._109"
            ],
            [
                "SOR-86-594",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-594"
            ],
            [
                "SOR-2010-91",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-91"
            ],
            [
                "SOR-96-337",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-337"
            ],
            [
                "SOR-90-739",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-739"
            ],
            [
                "SOR-81-707",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-707"
            ],
            [
                "C.R.C.,_c._1264",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1264"
            ],
            [
                "SOR-85-358",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-358"
            ],
            [
                "SOR-83-253",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-83-253"
            ],
            [
                "SOR-92-100",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-100"
            ],
            [
                "SI-2006-23",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-2006-23"
            ],
            [
                "SOR-93-325",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-325"
            ],
            [
                "SOR-2000-112",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-112"
            ],
            [
                "C.R.C.,_c._1384",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1384"
            ],
            [
                "C.R.C.,_c._114",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._114"
            ],
            [
                "SOR-89-488",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-488"
            ],
            [
                "SOR-81-568",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-568"
            ],
            [
                "SOR-85-414",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-414"
            ],
            [
                "C.R.C.,_c._1038",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1038"
            ],
            [
                "C.R.C.,_c._104",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._104"
            ],
            [
                "C.R.C.,_c._1381",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1381"
            ],
            [
                "SOR-2008-121",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2008-121"
            ],
            [
                "C.R.C.,_c._1375",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1375"
            ],
            [
                "SOR-2003-105",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2003-105"
            ],
            [
                "SOR-98-568",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-98-568"
            ],
            [
                "SOR-89-99",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-99"
            ],
            [
                "C.R.C.,_c._353",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._353"
            ],
            [
                "SOR-87-543",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-543"
            ],
            [
                "SOR-93-385",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-385"
            ],
            [
                "C.R.C.,_c._15",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._15"
            ],
            [
                "SOR-94-241",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-241"
            ],
            [
                "C.R.C.,_c._79",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._79"
            ],
            [
                "SOR-87-449",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-449"
            ],
            [
                "SOR-82-296",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-296"
            ],
            [
                "SOR-2006-102",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2006-102"
            ],
            [
                "C.R.C.,_c._1182",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1182"
            ],
            [
                "SOR-2014-104",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-104"
            ],
            [
                "SOR-81-710",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-710"
            ],
            [
                "SOR-2010-83",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-83"
            ],
            [
                "C.R.C.,_c._10",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._10"
            ],
            [
                "SOR-2006-139",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2006-139"
            ],
            [
                "C.R.C.,_c._1376",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1376"
            ],
            [
                "SOR-94-556",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-556"
            ],
            [
                "SOR-88-400",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-400"
            ],
            [
                "C.R.C.,_c._123",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._123"
            ],
            [
                "SOR-88-58",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-58"
            ],
            [
                "SOR-2005-232",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-232"
            ],
            [
                "SOR-86-631",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-631"
            ],
            [
                "SOR-2006-78",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2006-78"
            ],
            [
                "C.R.C.,_c._125",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._125"
            ],
            [
                "SOR-2012-95",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-95"
            ],
            [
                "C.R.C.,_c._356",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._356"
            ],
            [
                "C.R.C.,_c._1482",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1482"
            ],
            [
                "SOR-85-192",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-192"
            ],
            [
                "C.R.C.,_c._1494",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1494"
            ],
            [
                "SOR-2005-328",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-328"
            ],
            [
                "SOR-2010-120",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-120"
            ],
            [
                "C.R.C.,_c._1448",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1448"
            ],
            [
                "SOR-2014-234",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-234"
            ],
            [
                "C.R.C.,_c._398",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._398"
            ],
            [
                "C.R.C.,_c._92",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._92"
            ],
            [
                "C.R.C.,_c._4",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._4"
            ],
            [
                "SOR-80-9",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-80-9"
            ],
            [
                "SOR-2002-180",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-180"
            ],
            [
                "SOR-2001-518",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2001-518"
            ],
            [
                "SOR-88-125",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-125"
            ],
            [
                "SOR-87-604",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-604"
            ],
            [
                "SOR-88-124",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-124"
            ],
            [
                "SOR-2002-138",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-138"
            ],
            [
                "C.R.C.,_c._1195",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1195"
            ],
            [
                "SOR-80-482",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-80-482"
            ],
            [
                "SOR-2005-404",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-404"
            ],
            [
                "SOR-90-153",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-153"
            ],
            [
                "SOR-2005-180",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-180"
            ],
            [
                "C.R.C.,_c._113",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._113"
            ],
            [
                "C.R.C.,_c._1151",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1151"
            ],
            [
                "SOR-79-154",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-79-154"
            ],
            [
                "SOR-95-507",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-507"
            ],
            [
                "C.R.C.,_c._1148",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1148"
            ],
            [
                "SOR-2009-231",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2009-231"
            ],
            [
                "C.R.C.,_c._1405",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1405"
            ],
            [
                "SOR-2012-69",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-69"
            ],
            [
                "SOR-2003-51",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2003-51"
            ],
            [
                "C.R.C.,_c._116",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._116"
            ],
            [
                "C.R.C.,_c._88",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._88"
            ],
            [
                "SOR-81-567",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-567"
            ],
            [
                "SOR-88-509",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-509"
            ],
            [
                "SOR-2000-71",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-71"
            ],
            [
                "SOR-2004-212",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2004-212"
            ],
            [
                "SOR-98-569",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-98-569"
            ],
            [
                "SOR-81-472",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-472"
            ],
            [
                "SOR-88-447",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-447"
            ],
            [
                "SOR-2008-275",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2008-275"
            ],
            [
                "SOR-91-171",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-171"
            ],
            [
                "C.R.C.,_c._14",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._14"
            ],
            [
                "SOR-80-803",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-80-803"
            ],
            [
                "SOR-2000-132",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-132"
            ],
            [
                "SOR-84-253",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-253"
            ],
            [
                "C.R.C.,_c._1185",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1185"
            ],
            [
                "SOR-88-399",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-399"
            ],
            [
                "C.R.C.,_c._115",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._115"
            ],
            [
                "C.R.C.,_c._96",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._96"
            ],
            [
                "SOR-87-375",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-375"
            ],
            [
                "SOR-99-244",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-99-244"
            ],
            [
                "C.R.C.,_c._887",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._887"
            ],
            [
                "SOR-87-100",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-100"
            ],
            [
                "SOR-93-387",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-387"
            ],
            [
                "C.R.C.,_c._87",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._87"
            ],
            [
                "C.R.C.,_c._1498",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1498"
            ],
            [
                "SOR-2001-84",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2001-84"
            ],
            [
                "SOR-85-583",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-583"
            ],
            [
                "C.R.C.,_c._106",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._106"
            ],
            [
                "C.R.C.,_c._95",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._95"
            ],
            [
                "SOR-91-103",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-103"
            ],
            [
                "SOR-2005-226",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-226"
            ],
            [
                "SOR-96-334",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-334"
            ],
            [
                "C.R.C.,_c._16",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._16"
            ],
            [
                "SOR-91-488",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-488"
            ],
            [
                "SI-86-64",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-86-64"
            ],
            [
                "C.R.C.,_c._1472",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1472"
            ],
            [
                "SOR-92-68",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-68"
            ],
            [
                "C.R.C.,_c._1171",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1171"
            ],
            [
                "C.R.C.,_c._1564",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1564"
            ],
            [
                "SOR-2014-192",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-192"
            ],
            [
                "SOR-92-343",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-343"
            ],
            [
                "C.R.C.,_c._98",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._98"
            ],
            [
                "SOR-2010-127",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-127"
            ],
            [
                "SOR-2007-126",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-126"
            ],
            [
                "C.R.C.,_c._1225",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1225"
            ],
            [
                "SOR-2012-93",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-93"
            ],
            [
                "SOR-91-173",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-173"
            ],
            [
                "SOR-93-523",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-523"
            ],
            [
                "SOR-86-332",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-332"
            ],
            [
                "SOR-2004-86",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2004-86"
            ],
            [
                "SOR-84-5",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-5"
            ],
            [
                "SOR-93-410",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-410"
            ],
            [
                "SOR-91-104",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-104"
            ],
            [
                "C.R.C.,_c._1467",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1467"
            ],
            [
                "SOR-2010-227",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-227"
            ],
            [
                "SOR-85-184",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-184"
            ],
            [
                "SOR-90-818",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-818"
            ],
            [
                "C.R.C.,_c._355",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._355"
            ],
            [
                "SOR-98-348",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-98-348"
            ],
            [
                "C.R.C.,_c._118",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._118"
            ],
            [
                "SOR-93-327",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-327"
            ],
            [
                "C.R.C.,_c._81",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._81"
            ],
            [
                "SOR-2002-307",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-307"
            ],
            [
                "SOR-82-832",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-832"
            ],
            [
                "SOR-91-484",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-484"
            ],
            [
                "SOR-92-21",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-21"
            ],
            [
                "C.R.C.,_c._99",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._99"
            ],
            [
                "SOR-89-222",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-222"
            ],
            [
                "SOR-2011-203",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2011-203"
            ],
            [
                "SOR-96-446",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-446"
            ],
            [
                "SOR-94-591",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-591"
            ],
            [
                "SOR-81-167",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-167"
            ],
            [
                "C.R.C.,_c._121",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._121"
            ],
            [
                "SOR-94-123",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-123"
            ],
            [
                "SOR-95-506",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-506"
            ],
            [
                "SOR-94-496",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-496"
            ],
            [
                "SOR-2007-115",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-115"
            ],
            [
                "SOR-88-126",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-126"
            ],
            [
                "C.R.C.,_c._112",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._112"
            ],
            [
                "SOR-82-1015",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-1015"
            ],
            [
                "SOR-94-119",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-119"
            ],
            [
                "C.R.C.,_c._1266",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1266"
            ],
            [
                "SOR-80-310",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-80-310"
            ],
            [
                "C.R.C.,_c._101",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._101"
            ],
            [
                "SOR-2015-26",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2015-26"
            ],
            [
                "SOR-2009-321",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2009-321"
            ],
            [
                "SOR-93-522",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-522"
            ],
            [
                "SOR-2013-142",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2013-142"
            ],
            [
                "SOR-91-172",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-172"
            ],
            [
                "SOR-94-121",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-121"
            ],
            [
                "SOR-91-101",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-101"
            ],
            [
                "SOR-87-7",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-7"
            ],
            [
                "SOR-99-123",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-99-123"
            ],
            [
                "SOR-93-220",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-220"
            ],
            [
                "C.R.C.,_c._80",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._80"
            ],
            [
                "SOR-2001-207",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2001-207"
            ],
            [
                "SOR-96-133",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-133"
            ],
            [
                "SOR-2000-55",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-55"
            ],
            [
                "C.R.C.,_c._84",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._84"
            ],
            [
                "SOR-2007-128",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-128"
            ],
            [
                "C.R.C.,_c._1563",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1563"
            ],
            [
                "SOR-87-706",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-706"
            ],
            [
                "C.R.C.,_c._1378",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1378"
            ],
            [
                "C.R.C.,_c._1436",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1436"
            ],
            [
                "SI-85-202",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-85-202"
            ],
            [
                "SOR-82-712",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-712"
            ],
            [
                "SOR-2012-97",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-97"
            ],
            [
                "SI-80-8",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-80-8"
            ],
            [
                "SOR-88-450",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-450"
            ],
            [
                "C.R.C.,_c._1145",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1145"
            ],
            [
                "SOR-2012-92",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-92"
            ],
            [
                "C.R.C.,_c._89",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._89"
            ],
            [
                "C.R.C.,_c._1379",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1379"
            ],
            [
                "C.R.C.,_c._1495",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1495"
            ],
            [
                "SOR-2012-98",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-98"
            ],
            [
                "C.R.C.,_c._83",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._83"
            ],
            [
                "SOR-85-515",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-515"
            ],
            [
                "SOR-88-41",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-41"
            ],
            [
                "C.R.C.,_c._1382",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1382"
            ],
            [
                "SOR-84-901",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-901"
            ],
            [
                "C.R.C.,_c._1431",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1431"
            ],
            [
                "SOR-84-127",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-127"
            ],
            [
                "SOR-92-142",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-142"
            ],
            [
                "C.R.C.,_c._111",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._111"
            ],
            [
                "SOR-95-545",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-545"
            ],
            [
                "SOR-78-657",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-78-657"
            ],
            [
                "C.R.C.,_c._1465",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1465"
            ],
            [
                "C.R.C.,_c._93",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._93"
            ],
            [
                "C.R.C.,_c._1435",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1435"
            ],
            [
                "SOR-85-514",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-514"
            ],
            [
                "SOR-84-335",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-335"
            ],
            [
                "SOR-2001-154",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2001-154"
            ],
            [
                "SOR-2012-149",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-149"
            ],
            [
                "SOR-85-188",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-188"
            ],
            [
                "SOR-81-708",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-708"
            ],
            [
                "C.R.C.,_c._1566",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1566"
            ],
            [
                "SOR-90-793",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-793"
            ],
            [
                "SOR-2005-73",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-73"
            ],
            [
                "SOR-79-373",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-79-373"
            ],
            [
                "SOR-93-326",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-326"
            ],
            [
                "SOR-93-409",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-409"
            ],
            [
                "SOR-95-505",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-505"
            ],
            [
                "SOR-81-916",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-916"
            ],
            [
                "SOR-92-649",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-649"
            ],
            [
                "SOR-93-65",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-65"
            ],
            [
                "SOR-2000-260",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-260"
            ],
            [
                "SOR-95-559",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-559"
            ],
            [
                "SOR-93-524",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-524"
            ],
            [
                "SOR-2014-16",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-16"
            ],
            [
                "SOR-92-67",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-67"
            ],
            [
                "SOR-2005-134",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-134"
            ],
            [
                "SOR-91-253",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-91-253"
            ],
            [
                "SOR-2005-120",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-120"
            ],
            [
                "SOR-95-558",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-558"
            ],
            [
                "SOR-94-386",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-386"
            ],
            [
                "SOR-84-972",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-972"
            ],
            [
                "C.R.C.,_c._78",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._78"
            ],
            [
                "SOR-2012-96",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-96"
            ],
            [
                "SOR-78-417",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-78-417"
            ],
            [
                "C.R.C.,_c._1377",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1377"
            ],
            [
                "SOR-2012-91",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-91"
            ],
            [
                "SOR-81-948",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-948"
            ],
            [
                "SOR-95-149",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-149"
            ],
            [
                "SOR-87-603",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-603"
            ],
            [
                "SOR-2006-15",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2006-15"
            ],
            [
                "SOR-87-150",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-150"
            ],
            [
                "SOR-86-1004",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-1004"
            ],
            [
                "SOR-96-383",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-383"
            ],
            [
                "SOR-90-264",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-264"
            ],
            [
                "SOR-95-345",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-345"
            ],
            [
                "C.R.C.,_c._1231",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1231"
            ],
            [
                "C.R.C.,_c._77",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._77"
            ],
            [
                "C.R.C.,_c._90",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._90"
            ],
            [
                "C.R.C.,_c._82",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._82"
            ],
            [
                "SOR-95-495",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-495"
            ],
            [
                "SOR-88-590",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-590"
            ],
            [
                "SOR-92-22",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-22"
            ],
            [
                "SOR-2009-17",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2009-17"
            ],
            [
                "SOR-2004-144",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2004-144"
            ],
            [
                "SOR-78-771",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-78-771"
            ],
            [
                "SOR-87-605",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-605"
            ],
            [
                "SOR-2014-258",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-258"
            ],
            [
                "SOR-2013-198",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2013-198"
            ],
            [
                "SOR-2008-97",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2008-97"
            ],
            [
                "SOR-93-388",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-388"
            ],
            [
                "SOR-2011-237",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2011-237"
            ],
            [
                "SOR-95-405",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-405"
            ],
            [
                "C.R.C.,_c._1486",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1486"
            ],
            [
                "SOR-90-794",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-90-794"
            ],
            [
                "SOR-93-408",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-408"
            ],
            [
                "C.R.C.,_c._886",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._886"
            ],
            [
                "SOR-99-53",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-99-53"
            ],
            [
                "C.R.C.,_c._1232",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1232"
            ],
            [
                "C.R.C.,_c._354",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._354"
            ],
            [
                "SOR-88-101",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-101"
            ],
            [
                "SOR-2011-87",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2011-87"
            ],
            [
                "SOR-84-970",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-970"
            ],
            [
                "SOR-2016-317",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2016-317"
            ],
            [
                "SOR-86-922",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-922"
            ],
            [
                "C.R.C.,_c._1418",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1418"
            ],
            [
                "SOR-93-293",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-293"
            ],
            [
                "SOR-89-225",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-225"
            ],
            [
                "SOR-2014-276",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-276"
            ],
            [
                "SOR-86-1026",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-1026"
            ],
            [
                "SOR-2009-202",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2009-202"
            ],
            [
                "SOR-2002-172",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-172"
            ],
            [
                "C.R.C.,_c._1432",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1432"
            ],
            [
                "SOR-96-433",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-433"
            ],
            [
                "SOR-85-658",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-85-658"
            ],
            [
                "SOR-95-275",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-275"
            ],
            [
                "SOR-95-508",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-508"
            ],
            [
                "SOR-88-398",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-398"
            ],
            [
                "SOR-2007-127",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-127"
            ],
            [
                "C.R.C.,_c._102",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._102"
            ],
            [
                "C.R.C.,_c._1268",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1268"
            ],
            [
                "SOR-92-648",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-648"
            ],
            [
                "SOR-2007-99",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-99"
            ],
            [
                "C.R.C.,_c._103",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._103"
            ],
            [
                "SOR-2012-94",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2012-94"
            ],
            [
                "SOR-87-453",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-453"
            ],
            [
                "SOR-2013-141",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2013-141"
            ],
            [
                "SOR-81-706",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-706"
            ],
            [
                "SOR-95-346",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-346"
            ],
            [
                "C.R.C.,_c._117",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._117"
            ],
            [
                "C.R.C.,_c._1146",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1146"
            ],
            [
                "SOR-2014-275",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-275"
            ],
            [
                "SOR-87-602",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-602"
            ],
            [
                "SOR-2010-90",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2010-90"
            ],
            [
                "SOR-81-364",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-364"
            ],
            [
                "C.R.C.,_c._122",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._122"
            ],
            [
                "SI-81-61",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-81-61"
            ],
            [
                "C.R.C.,_c._1147",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1147"
            ],
            [
                "SOR-94-42",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-42"
            ],
            [
                "SOR-89-408",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-408"
            ],
            [
                "SOR-82-1038",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-1038"
            ],
            [
                "SOR-82-480",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-480"
            ],
            [
                "SOR-83-810",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-83-810"
            ],
            [
                "SOR-2007-31",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-31"
            ],
            [
                "C.R.C.,_c._1152",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1152"
            ],
            [
                "SOR-84-567",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-567"
            ],
            [
                "C.R.C.,_c._1380",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1380"
            ],
            [
                "SOR-87-184",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-184"
            ],
            [
                "SOR-2011-318",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2011-318"
            ],
            [
                "SOR-95-347",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-347"
            ],
            [
                "C.R.C.,_c._1422",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1422"
            ],
            [
                "SOR-99-335",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-99-335"
            ],
            [
                "SOR-86-1135",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-86-1135"
            ],
            [
                "SOR-2005-313",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2005-313"
            ],
            [
                "C.R.C.,_c._1416",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1416"
            ],
            [
                "SI-89-98",
                "https://laws-lois.justice.gc.ca/eng/regulations/SI-89-98"
            ],
            [
                "SOR-2014-55",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-55"
            ],
            [
                "SOR-89-98",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-98"
            ],
            [
                "SOR-93-74",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-93-74"
            ],
            [
                "C.R.C.,_c._91",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._91"
            ],
            [
                "SOR-79-15",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-79-15"
            ],
            [
                "C.R.C.,_c._75",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._75"
            ],
            [
                "SOR-92-69",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-92-69"
            ],
            [
                "SOR-2014-94",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-94"
            ],
            [
                "SOR-87-705",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-87-705"
            ],
            [
                "SOR-2002-47",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2002-47"
            ],
            [
                "SOR-96-401",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-401"
            ],
            [
                "SOR-2004-130",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2004-130"
            ],
            [
                "SOR-82-276",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-276"
            ],
            [
                "SOR-95-586",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-95-586"
            ],
            [
                "SOR-2014-233",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-233"
            ],
            [
                "SOR-80-902",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-80-902"
            ],
            [
                "SOR-2001-297",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2001-297"
            ],
            [
                "SOR-88-148",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-88-148"
            ],
            [
                "C.R.C.,_c._1430",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1430"
            ],
            [
                "SOR-79-817",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-79-817"
            ],
            [
                "SOR-2014-37",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2014-37"
            ],
            [
                "SOR-81-452",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-81-452"
            ],
            [
                "SOR-84-734",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-84-734"
            ],
            [
                "SOR-99-101",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-99-101"
            ],
            [
                "SOR-2008-120",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2008-120"
            ],
            [
                "SOR-89-236",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-89-236"
            ],
            [
                "SOR-2000-265",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2000-265"
            ],
            [
                "SOR-2007-125",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-2007-125"
            ],
            [
                "SOR-96-338",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-96-338"
            ],
            [
                "SOR-82-468",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-82-468"
            ],
            [
                "C.R.C.,_c._1270",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._1270"
            ],
            [
                "SOR-94-120",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-94-120"
            ],
            [
                "SOR-79-101",
                "https://laws-lois.justice.gc.ca/eng/regulations/SOR-79-101"
            ],
            [
                "C.R.C.,_c._105",
                "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.,_c._105"
            ]
            ]
        }
        }
        # ,{
        #     "name": "another_use_case",
        #     "is_default": True,           #<----- If True, this will be the default database in the app (if true for multiple databases, the first one will be the default)
        #     "save_html": True,            #<----- If True, the html files of all web pages will be saved in the "outputs" folder
        #     "languages": ["en"],
        #     "ressource_name": {
        #         "en": "Another use case"
        #     },
        #     "pdf": {
        #         "en": [
        #             "https://www.example.com/pdf/example.pdf",  #<----- Remote pdf
        #             "C:/test.pdf"                               #<----- Local pdf file
        #             "../use_case_x/"                            #<----- Local folder with pdfs
        #         ] 
        #     }
        # }
    ]

@dataclass
class FilteredMTEB:
    url="http://mteb-leaderboard.hf.space/?benchmark_name=MTEB%28Multilingual%2C+v1%29"
    additional_filters=["ordered by retrieval score", "availability=open only"]

class CustomEmbeddingFunction(EmbeddingFunction):

    def __init__(self, model_name, trust_remote_code=False):
        super().__init__()
        self.model_name = model_name
        self.trust_remote_code = trust_remote_code
    
    def __call__(self, input_):
        embeddings =SentenceTransformer(self.model_name, trust_remote_code=self.trust_remote_code).encode(input_)
        return embeddings


class EmbeddingModel:

    def __init__(self, model_name:str, trust_remote_code:bool=False):
        self.model_name = model_name
        self.trust_remote_code = trust_remote_code
        self.model=SentenceTransformer(self.model_name, trust_remote_code=self.trust_remote_code)
        self.model_chroma_callable=CustomEmbeddingFunction(model_name=self.model_name, trust_remote_code=self.trust_remote_code)

        try:
            self.max_seq_length=self.model.max_seq_length
        except Exception as e:
            print(e)
        try:
            self.used_seq_length=self.model.max_seq_length
        except Exception as e:
            print(e)
        try:
            self.dimensions=self.model.get_sentence_embedding_dimension()
        except Exception as e:
            print(e)
        if self.model.similarity_fn_name is None:
            self.model.similarity_fn_name = ModelsConfig.models_similarity_fn[model_name]
            print(f"Model similarity function name: {self.model.similarity_fn_name}")


if __name__ == "__main__":
        
    for k, v in ModelsConfig.models.items():
        try:
            model_instance = EmbeddingModel(model_name=v, trust_remote_code=True)
            print(f"\nModel name: {model_instance.model_name}")
            print(f"Model max sequence length: {model_instance.max_seq_length}")
            print(f"Model embedding dimensions: {model_instance.dimensions}")
            if model_instance.model.similarity_fn_name is not None:
                print(f"Model similarity function name: {model_instance.model.similarity_fn_name}")
        except Exception as e:
            print("\n"+ str(e))
        if model_instance.model.similarity_fn_name is None:
            model_instance.similarity_fn_name = ModelsConfig.models_similarity_fn[k]
            print(f"Model similarity function name: {model_instance.similarity_fn_name}")